### ISSUE TITLE
How soon will the codes and articles be published, please?

### ISSUE THREAD

**Issue by ppsychoo** [WentaoTan/MLLM4Text-ReID#1]

**Comment by TwT-JD** [comment]
Hello, thank you for your interest in our work. We appreciate your attention. Our work needs to go through the company's review process before it can be open-sourced. We are currently undergoing this process, and we expect to release the article and code before May. We will notify you at that time. Thank you for your understanding and patience.

**Comment by WentaoTan** [comment]
We are pleased to inform you that the code and article have been open-sourced. If you have any further questions, please feel free to ask. Thank you!
