### ISSUE TITLE
About the model weights

### ISSUE THREAD

**Issue by shuanglinyan** [WentaoTan/MLLM4Text-ReID#4]
Thanks for your great work and open source code, can I get the model weights file you trained on LUPerson-MLLM?

**Comment by WentaoTan** [comment]
Thank you for your attention! 
As this article is a collaboration with JD, there are strict regulations regarding model open-sourcing. In fact, the application for the model's open-source release is already in progress. Please be patient, and I will inform you immediately once the application is approved. 
Thank you!

**Comment by shuanglinyan** [comment]
Thank you very much for your reply. Looking forward to it.

**Comment by WentaoTan** [comment]
Hello! The pretrained model checkpoints can be found here: https://huggingface.co/datasets/TwT-6/MLLM4Text-ReID.

**Comment by shuanglinyan** [comment]
Ok, thank you!
