### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by ritaanthem** [WentaoTan/MLLM4Text-ReID#6]
作者您好，我在本地下载了LUPerson和caption，使用您公布的代码进行训练，但距离paper中的性能会差一至两个点。我发现您在paper的Implementation Details部分描述的是"8 TITAN-V GPUs, with 64 images per GPU"，这样总的batch size是512，但在run.sh 中的配置是 --batch_size 256。请问batch size应该设置成多大可以更加接近paper中的结果？

**Comment by WentaoTan** [comment]
您好！我们也遇到了相似的情况。
我们曾经使用不同的机器进行实验，发现即便是同样的配置，两次不同的实验的性能的确是可以相差到1-2%。您可以多尝试几次实验和不同的种子。
另外，我们模型的开源也正在推进，计划下星期即可公布论文中的模型；届时我将通知您一声，如有需要可以直接使用我们提供的模型参数。
接着，run.sh中的配置是我的笔误。如您所见他是一个testing脚本（log name），在这里向您致歉。
最后，在我们的实验里，batch size=64*GPUs是较好的（我们将要公布的模型亦是这个配置）。


再次道歉！同时更感谢您指出错误，帮我们斧正了代码。谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月29日(星期六) 晚上8:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [WentaoTan/MLLM4Text-ReID] Batch Size (Issue #6)














 
作者您好，我在本地下载了LUPerson和caption，使用您公布的代码进行训练，但距离paper中的性能会差一至两个点。我发现您在paper的Implementation Details部分描述的是"8 TITAN-V GPUs, with 64 images per GPU"，这样总的batch size是512，但在run.sh 中的配置是 --batch_size 256。请问batch size应该设置成多大可以更加接近paper中的结果？

**Comment by ritaanthem** [comment]
好的，非常感谢您的回复。期待模型参数的开源！

**Comment by WentaoTan** [comment]
您好！现在您可以从这个地方下载到模型参数啦： https://huggingface.co/datasets/TwT-6/MLLM4Text-ReID.

**Comment by ritaanthem** [comment]
非常感谢！
