### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by caoyan1998** [WentaoTan/MLLM4Text-ReID#7]
在我执行sh finetune.sh 后, (best0.pth, best1.pth,best2.pth)也已经下载放置好, 但是会出现 : 
**RuntimeError: Error(s) in loading state_dict for IRRA:**
        **Missing key(s) in state_dict:** "classifier.weight", "classifier.bias", "cross_attn.in_proj_weight", "cross_attn.in_proj_bias", "cross_attn.out_proj.weight", "cross_attn.out_proj.bias", "cross_modal_transformer.resblocks.0.attn.in_proj_weight", "cross_modal_transformer.resblocks.0.attn.in_proj_bias", "cross_modal_transformer.resblocks.0.attn.out_proj.weight", "cross_modal_transformer.resblocks.0.attn.out_proj.bias", "cross_modal_transformer.resblocks.0.ln_1.weight", "cross_modal_transformer.resblocks.0.ln_1.bias", "cross_modal_transformer.resblocks.0.mlp.c_fc.weight", "cross_modal_transformer.resblocks.0.mlp.c_fc.bias", "cross_modal_transformer.resblocks.0.mlp.c_proj.weight", "cross_modal_transformer.resblocks.0.mlp.c_proj.bias", "cross_modal_transformer.resblocks.0.ln_2.weight", "cross_modal_transformer.resblocks.0.ln_2.bias", "cross_modal_transformer.resblocks.1.attn.in_proj_weight", "cross_modal_transformer.resblocks.1.attn.in_proj_bias", "cross_modal_transformer.resblocks.1.attn.out_proj.weight", "cross_modal_transformer.resblocks.1.attn.out_proj.bias", "cross_modal_transformer.resblocks.1.ln_1.weight", "cross_modal_transformer.resblocks.1.ln_1.bias", "cross_modal_transformer.resblocks.1.mlp.c_fc.weight", "cross_modal_transformer.resblocks.1.mlp.c_fc.bias", "cross_modal_transformer.resblocks.1.mlp.c_proj.weight", "cross_modal_transformer.resblocks.1.mlp.c_proj.bias", "cross_modal_transformer.resblocks.1.ln_2.weight", "cross_modal_transformer.resblocks.1.ln_2.bias", "cross_modal_transformer.resblocks.2.attn.in_proj_weight", "cross_modal_transformer.resblocks.2.attn.in_proj_bias", "cross_modal_transformer.resblocks.2.attn.out_proj.weight", "cross_modal_transformer.resblocks.2.attn.out_proj.bias", "cross_modal_transformer.resblocks.2.ln_1.weight", "cross_modal_transformer.resblocks.2.ln_1.bias", "cross_modal_transformer.resblocks.2.mlp.c_fc.weight", "cross_modal_transformer.resblocks.2.mlp.c_fc.bias", "cross_modal_transformer.resblocks.2.mlp.c_proj.weight", "cross_modal_transformer.resblocks.2.mlp.c_proj.bias", "cross_modal_transformer.resblocks.2.ln_2.weight", "cross_modal_transformer.resblocks.2.ln_2.bias", "cross_modal_transformer.resblocks.3.attn.in_proj_weight", "cross_modal_transformer.resblocks.3.attn.in_proj_bias", "cross_modal_transformer.resblocks.3.attn.out_proj.weight", "cross_modal_transformer.resblocks.3.attn.out_proj.bias", "cross_modal_transformer.resblocks.3.ln_1.weight", "cross_modal_transformer.resblocks.3.ln_1.bias", "cross_modal_transformer.resblocks.3.mlp.c_fc.weight", "cross_modal_transformer.resblocks.3.mlp.c_fc.bias", "cross_modal_transformer.resblocks.3.mlp.c_proj.weight", "cross_modal_transformer.resblocks.3.mlp.c_proj.bias", "cross_modal_transformer.resblocks.3.ln_2.weight", "cross_modal_transformer.resblocks.3.ln_2.bias", "ln_pre_t.weight", "ln_pre_t.bias", "ln_pre_i.weight", "ln_pre_i.bias", "ln_post.weight", "ln_post.bias", "mlm_head.dense.weight", "mlm_head.dense.bias", "mlm_head.ln.weight", "mlm_head.ln.bias", "mlm_head.fc.weight", "mlm_head.fc.bias".

**Comment by WentaoTan** [comment]
预训练模型结构和IRRA模型结构不同。预训练模型是全部的CLIP。IRRA是CLIP+cross_model+fc+mlm_head。因此会出现说key missing.

解决办法就是在finetune.py的load模型参数的地方，加上strict=False即可。
如model.load_state_dict(param_dict, False)

**Comment by kapbl** [comment]
谢谢解答, 感谢!
