### ISSUE TITLE
code to use Shikra for image captioning

### ISSUE THREAD

**Issue by Zoesxw** [WentaoTan/MLLM4Text-ReID#8]
Thank you for your excellent work! 
You provide the code to use Qwen for image captioning, can you provide the code for Shikra?

**Comment by WentaoTan** [comment]
The code for generating captions using Shikra is much more complex compared to Qwen. According to Shikra's GitHub repository, we first need to deploy it as a local server, and then use a local client to call the server's API. Please refer to the Server-Client Demo at https://github.com/shikras/shikra for more details.

**Comment by Zoesxw** [comment]
Thank you for your reply
